#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck disable=SC1090
source "${ROOT_DIR}/wasm/scripts/env.sh"

${ROOT_DIR}/wasm/scripts/generate_wasm_pri.sh

# PTHREAD pool size is configured via qmake vars in wasm/konclude_wasm_flags.pri.

JOBS="${JOBS:-}"
if [[ -z "${JOBS}" ]]; then
	if command -v nproc >/dev/null 2>&1; then
		JOBS="$(nproc)"
	else
		JOBS="$(sysctl -n hw.ncpu 2>/dev/null || echo 2)"
	fi
fi

BUILD_DIR="${ROOT_DIR}/wasm/build/mt"
DEST_DIR="${ROOT_DIR}/wasm/dist/mt"

mkdir -p "${BUILD_DIR}" "${DEST_DIR}"
pushd "${BUILD_DIR}" >/dev/null

	"${QMAKE}" "${ROOT_DIR}/KoncludeWasm.pro" \
		KONCLUDE_WASM_THREADS=1 \
		KONCLUDE_WASM_TARGET=konclude_mt \
		KONCLUDE_WASM_DESTDIR="${DEST_DIR}" \
		KONCLUDE_WASM_TOTAL_MEMORY="${KONCLUDE_WASM_TOTAL_MEMORY}" \
		KONCLUDE_WASM_PTHREAD_POOL="${KONCLUDE_WASM_PTHREAD_POOL:-}" \
		KONCLUDE_WASM_PTHREAD_OVERHEAD="${KONCLUDE_WASM_PTHREAD_OVERHEAD:-}" \
		KONCLUDE_WASM_PROCESSOR_COUNT="${KONCLUDE_WASM_PROCESSOR_COUNT:-}" \
		KONCLUDE_WASM_PTHREAD_STRICT="${KONCLUDE_WASM_PTHREAD_STRICT:-}" \
		KONCLUDE_WASM_DEBUG="${KONCLUDE_WASM_DEBUG:-}" \
		KONCLUDE_WASM_LTO="${KONCLUDE_WASM_LTO:-}" \
		KONCLUDE_WASM_LINK_O3="${KONCLUDE_WASM_LINK_O3:-}" \
		KONCLUDE_WASM_SIMD="${KONCLUDE_WASM_SIMD:-}" \
		KONCLUDE_WASM_EXCEPTIONS="${KONCLUDE_WASM_EXCEPTIONS:-}" \
		KONCLUDE_WASM_WASM_EXCEPTIONS="${KONCLUDE_WASM_WASM_EXCEPTIONS:-}" \
		KONCLUDE_WASM_LONGJMP="${KONCLUDE_WASM_LONGJMP:-}" \
		KONCLUDE_WASM_STACK_SIZE="${KONCLUDE_WASM_STACK_SIZE:-}" \
		KONCLUDE_WASM_PTHREAD_STACK_SIZE="${KONCLUDE_WASM_PTHREAD_STACK_SIZE:-}" \
		KONCLUDE_WASM_MALLOC="${KONCLUDE_WASM_MALLOC:-}" \
		KONCLUDE_WASM_TABLE_GROWTH="${KONCLUDE_WASM_TABLE_GROWTH:-}" \
		KONCLUDE_WASM_FP_CASTS="${KONCLUDE_WASM_FP_CASTS:-}" \
		KONCLUDE_WASM_RESERVE_POLICY="${KONCLUDE_WASM_RESERVE_POLICY:-}"

make -j"${JOBS}"

popd >/dev/null
