#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PRESET_EMSDK_VERSION="${EMSDK_VERSION:-}"
PRESET_QT_VERSION="${QT_VERSION:-}"
PRESET_QT_SRC_URL="${QT_SRC_URL:-}"
PRESET_QT_SRC_DIR="${QT_SRC_DIR:-}"
PRESET_KONCLUDE_WASM_TOTAL_MEMORY="${KONCLUDE_WASM_TOTAL_MEMORY:-}"
PRESET_KONCLUDE_WASM_PTHREAD_POOL="${KONCLUDE_WASM_PTHREAD_POOL:-}"
PRESET_KONCLUDE_WASM_PTHREAD_OVERHEAD="${KONCLUDE_WASM_PTHREAD_OVERHEAD:-}"
PRESET_KONCLUDE_WASM_PROCESSOR_COUNT="${KONCLUDE_WASM_PROCESSOR_COUNT:-}"
PRESET_KONCLUDE_WASM_PTHREAD_STRICT="${KONCLUDE_WASM_PTHREAD_STRICT:-}"
PRESET_KONCLUDE_WASM_DEBUG="${KONCLUDE_WASM_DEBUG:-}"
PRESET_KONCLUDE_WASM_EXCEPTIONS="${KONCLUDE_WASM_EXCEPTIONS:-}"
PRESET_KONCLUDE_WASM_STACK_SIZE="${KONCLUDE_WASM_STACK_SIZE:-}"
PRESET_KONCLUDE_WASM_PTHREAD_STACK_SIZE="${KONCLUDE_WASM_PTHREAD_STACK_SIZE:-}"
PRESET_KONCLUDE_WASM_WASM_EXCEPTIONS="${KONCLUDE_WASM_WASM_EXCEPTIONS:-}"
PRESET_KONCLUDE_WASM_LONGJMP="${KONCLUDE_WASM_LONGJMP:-}"

# shellcheck disable=SC1090
source "${ROOT_DIR}/wasm/versions.env"

# Allow environment overrides for build parameters.
EMSDK_VERSION="${PRESET_EMSDK_VERSION:-${EMSDK_VERSION}}"
QT_VERSION="${PRESET_QT_VERSION:-${QT_VERSION}}"
QT_SRC_URL="${PRESET_QT_SRC_URL:-${QT_SRC_URL}}"
QT_SRC_DIR="${PRESET_QT_SRC_DIR:-${QT_SRC_DIR}}"
KONCLUDE_WASM_TOTAL_MEMORY="${PRESET_KONCLUDE_WASM_TOTAL_MEMORY:-${KONCLUDE_WASM_TOTAL_MEMORY}}"
KONCLUDE_WASM_PTHREAD_POOL="${PRESET_KONCLUDE_WASM_PTHREAD_POOL:-${KONCLUDE_WASM_PTHREAD_POOL}}"
KONCLUDE_WASM_PTHREAD_OVERHEAD="${PRESET_KONCLUDE_WASM_PTHREAD_OVERHEAD:-${KONCLUDE_WASM_PTHREAD_OVERHEAD:-}}"
KONCLUDE_WASM_PROCESSOR_COUNT="${PRESET_KONCLUDE_WASM_PROCESSOR_COUNT:-${KONCLUDE_WASM_PROCESSOR_COUNT:-}}"
KONCLUDE_WASM_PTHREAD_STRICT="${PRESET_KONCLUDE_WASM_PTHREAD_STRICT:-${KONCLUDE_WASM_PTHREAD_STRICT:-}}"
KONCLUDE_WASM_DEBUG="${PRESET_KONCLUDE_WASM_DEBUG:-${KONCLUDE_WASM_DEBUG:-}}"
KONCLUDE_WASM_EXCEPTIONS="${PRESET_KONCLUDE_WASM_EXCEPTIONS:-${KONCLUDE_WASM_EXCEPTIONS:-}}"
KONCLUDE_WASM_STACK_SIZE="${PRESET_KONCLUDE_WASM_STACK_SIZE:-${KONCLUDE_WASM_STACK_SIZE:-}}"
KONCLUDE_WASM_PTHREAD_STACK_SIZE="${PRESET_KONCLUDE_WASM_PTHREAD_STACK_SIZE:-${KONCLUDE_WASM_PTHREAD_STACK_SIZE:-}}"
KONCLUDE_WASM_WASM_EXCEPTIONS="${PRESET_KONCLUDE_WASM_WASM_EXCEPTIONS:-${KONCLUDE_WASM_WASM_EXCEPTIONS:-}}"
KONCLUDE_WASM_LONGJMP="${PRESET_KONCLUDE_WASM_LONGJMP:-${KONCLUDE_WASM_LONGJMP:-}}"

if [[ -z "${KONCLUDE_WASM_PTHREAD_POOL}" ]]; then
	KONCLUDE_WASM_PTHREAD_POOL="auto"
fi

IMAGE_TAG="${IMAGE_TAG:-konclude-wasm-build:qt5.15}"

docker build \
	-f "${ROOT_DIR}/wasm/docker/Dockerfile" \
	-t "${IMAGE_TAG}" \
	--build-arg EMSDK_VERSION="${EMSDK_VERSION}" \
	--build-arg QT_VERSION="${QT_VERSION}" \
	--build-arg QT_SRC_URL="${QT_SRC_URL}" \
	--build-arg QT_SRC_DIR="${QT_SRC_DIR}" \
	--build-arg KONCLUDE_WASM_TOTAL_MEMORY="${KONCLUDE_WASM_TOTAL_MEMORY}" \
	--build-arg KONCLUDE_WASM_PTHREAD_POOL="${KONCLUDE_WASM_PTHREAD_POOL}" \
	--build-arg KONCLUDE_WASM_PTHREAD_OVERHEAD="${KONCLUDE_WASM_PTHREAD_OVERHEAD}" \
	--build-arg KONCLUDE_WASM_PROCESSOR_COUNT="${KONCLUDE_WASM_PROCESSOR_COUNT}" \
	--build-arg KONCLUDE_WASM_PTHREAD_STRICT="${KONCLUDE_WASM_PTHREAD_STRICT}" \
	--build-arg KONCLUDE_WASM_DEBUG="${KONCLUDE_WASM_DEBUG}" \
	--build-arg KONCLUDE_WASM_EXCEPTIONS="${KONCLUDE_WASM_EXCEPTIONS}" \
	--build-arg KONCLUDE_WASM_STACK_SIZE="${KONCLUDE_WASM_STACK_SIZE}" \
	--build-arg KONCLUDE_WASM_PTHREAD_STACK_SIZE="${KONCLUDE_WASM_PTHREAD_STACK_SIZE}" \
	--build-arg KONCLUDE_WASM_WASM_EXCEPTIONS="${KONCLUDE_WASM_WASM_EXCEPTIONS}" \
	--build-arg KONCLUDE_WASM_LONGJMP="${KONCLUDE_WASM_LONGJMP}" \
	"${ROOT_DIR}"

CONTAINER_ID="$(docker create "${IMAGE_TAG}" /bin/true)"
rm -rf "${ROOT_DIR}/wasm/dist"
mkdir -p "${ROOT_DIR}/wasm/dist"
docker cp "${CONTAINER_ID}:/out/." "${ROOT_DIR}/wasm/dist"
docker rm "${CONTAINER_ID}"
