#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Optional defaults pinned in wasm/versions.env (allow env overrides).
PRESET_EMSDK_VERSION="${EMSDK_VERSION:-}"
PRESET_QT_VERSION="${QT_VERSION:-}"
PRESET_QT_SRC_URL="${QT_SRC_URL:-}"
PRESET_QT_SRC_DIR="${QT_SRC_DIR:-}"
PRESET_KONCLUDE_WASM_TOTAL_MEMORY="${KONCLUDE_WASM_TOTAL_MEMORY:-}"
PRESET_KONCLUDE_WASM_PTHREAD_POOL="${KONCLUDE_WASM_PTHREAD_POOL:-}"
PRESET_KONCLUDE_WASM_PROCESSOR_COUNT="${KONCLUDE_WASM_PROCESSOR_COUNT:-}"
PRESET_KONCLUDE_WASM_PTHREAD_STRICT="${KONCLUDE_WASM_PTHREAD_STRICT:-}"

# shellcheck disable=SC1090
source "${ROOT_DIR}/wasm/versions.env"

EMSDK_VERSION="${PRESET_EMSDK_VERSION:-${EMSDK_VERSION}}"
QT_VERSION="${PRESET_QT_VERSION:-${QT_VERSION}}"
QT_SRC_URL="${PRESET_QT_SRC_URL:-${QT_SRC_URL}}"
QT_SRC_DIR="${PRESET_QT_SRC_DIR:-${QT_SRC_DIR}}"
KONCLUDE_WASM_TOTAL_MEMORY="${PRESET_KONCLUDE_WASM_TOTAL_MEMORY:-${KONCLUDE_WASM_TOTAL_MEMORY}}"
KONCLUDE_WASM_PTHREAD_POOL="${PRESET_KONCLUDE_WASM_PTHREAD_POOL:-${KONCLUDE_WASM_PTHREAD_POOL}}"
KONCLUDE_WASM_PROCESSOR_COUNT="${PRESET_KONCLUDE_WASM_PROCESSOR_COUNT:-${KONCLUDE_WASM_PROCESSOR_COUNT:-}}"
KONCLUDE_WASM_PTHREAD_STRICT="${PRESET_KONCLUDE_WASM_PTHREAD_STRICT:-${KONCLUDE_WASM_PTHREAD_STRICT:-}}"

: "${EMSDK_DIR:?Set EMSDK_DIR to your emsdk path (e.g., /opt/emsdk)}"
: "${QT_WASM_DIR:?Set QT_WASM_DIR to your Qt 5.15 wasm prefix (e.g., /opt/qt-wasm)}"

# Load emsdk environment (emcc, node, etc.).
# shellcheck disable=SC1090
source "${EMSDK_DIR}/emsdk_env.sh"

export PATH="${QT_WASM_DIR}/bin:${PATH}"
export QMAKE="${QT_WASM_DIR}/bin/qmake"

# Pass default memory sizing into qmake if set.
export KONCLUDE_WASM_TOTAL_MEMORY
export KONCLUDE_WASM_PTHREAD_POOL
export KONCLUDE_WASM_PROCESSOR_COUNT
export KONCLUDE_WASM_PTHREAD_STRICT
