#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Optional defaults pinned in wasm/versions.env (allow env overrides).
PRESET_EMSDK_VERSION="${EMSDK_VERSION:-}"
PRESET_QT_VERSION="${QT_VERSION:-}"
PRESET_QT_SRC_URL="${QT_SRC_URL:-}"
PRESET_QT_SRC_DIR="${QT_SRC_DIR:-}"
PRESET_KONCLUDE_WASM_TOTAL_MEMORY="${KONCLUDE_WASM_TOTAL_MEMORY:-}"
PRESET_KONCLUDE_WASM_PTHREAD_POOL="${KONCLUDE_WASM_PTHREAD_POOL:-}"
PRESET_KONCLUDE_WASM_PTHREAD_OVERHEAD="${KONCLUDE_WASM_PTHREAD_OVERHEAD:-}"
PRESET_KONCLUDE_WASM_PROCESSOR_COUNT="${KONCLUDE_WASM_PROCESSOR_COUNT:-}"
PRESET_KONCLUDE_WASM_PTHREAD_STRICT="${KONCLUDE_WASM_PTHREAD_STRICT:-}"
PRESET_KONCLUDE_WASM_DEBUG="${KONCLUDE_WASM_DEBUG:-}"
PRESET_KONCLUDE_WASM_EXCEPTIONS="${KONCLUDE_WASM_EXCEPTIONS:-}"
PRESET_KONCLUDE_WASM_WASM_EXCEPTIONS="${KONCLUDE_WASM_WASM_EXCEPTIONS:-}"
PRESET_KONCLUDE_WASM_LONGJMP="${KONCLUDE_WASM_LONGJMP:-}"
PRESET_KONCLUDE_WASM_STACK_SIZE="${KONCLUDE_WASM_STACK_SIZE:-}"
PRESET_KONCLUDE_WASM_PTHREAD_STACK_SIZE="${KONCLUDE_WASM_PTHREAD_STACK_SIZE:-}"

# shellcheck disable=SC1090
source "${ROOT_DIR}/wasm/versions.env"

EMSDK_VERSION="${PRESET_EMSDK_VERSION:-${EMSDK_VERSION}}"
QT_VERSION="${PRESET_QT_VERSION:-${QT_VERSION}}"
QT_SRC_URL="${PRESET_QT_SRC_URL:-${QT_SRC_URL}}"
QT_SRC_DIR="${PRESET_QT_SRC_DIR:-${QT_SRC_DIR}}"
KONCLUDE_WASM_TOTAL_MEMORY="${PRESET_KONCLUDE_WASM_TOTAL_MEMORY:-${KONCLUDE_WASM_TOTAL_MEMORY}}"
KONCLUDE_WASM_PTHREAD_POOL="${PRESET_KONCLUDE_WASM_PTHREAD_POOL:-${KONCLUDE_WASM_PTHREAD_POOL}}"
KONCLUDE_WASM_PTHREAD_OVERHEAD="${PRESET_KONCLUDE_WASM_PTHREAD_OVERHEAD:-${KONCLUDE_WASM_PTHREAD_OVERHEAD:-}}"
KONCLUDE_WASM_PROCESSOR_COUNT="${PRESET_KONCLUDE_WASM_PROCESSOR_COUNT:-${KONCLUDE_WASM_PROCESSOR_COUNT:-}}"
KONCLUDE_WASM_PTHREAD_STRICT="${PRESET_KONCLUDE_WASM_PTHREAD_STRICT:-${KONCLUDE_WASM_PTHREAD_STRICT:-}}"
KONCLUDE_WASM_DEBUG="${PRESET_KONCLUDE_WASM_DEBUG:-${KONCLUDE_WASM_DEBUG:-}}"
KONCLUDE_WASM_EXCEPTIONS="${PRESET_KONCLUDE_WASM_EXCEPTIONS:-${KONCLUDE_WASM_EXCEPTIONS:-}}"
KONCLUDE_WASM_WASM_EXCEPTIONS="${PRESET_KONCLUDE_WASM_WASM_EXCEPTIONS:-${KONCLUDE_WASM_WASM_EXCEPTIONS:-}}"
KONCLUDE_WASM_LONGJMP="${PRESET_KONCLUDE_WASM_LONGJMP:-${KONCLUDE_WASM_LONGJMP:-}}"
KONCLUDE_WASM_STACK_SIZE="${PRESET_KONCLUDE_WASM_STACK_SIZE:-${KONCLUDE_WASM_STACK_SIZE:-}}"
KONCLUDE_WASM_PTHREAD_STACK_SIZE="${PRESET_KONCLUDE_WASM_PTHREAD_STACK_SIZE:-${KONCLUDE_WASM_PTHREAD_STACK_SIZE:-}}"

if [[ -z "${KONCLUDE_WASM_PTHREAD_POOL}" ]]; then
	KONCLUDE_WASM_PTHREAD_POOL="auto"
fi

# Newer emsdk_env.sh variants clear EMSDK_DIR but set EMSDK instead.
if [[ -z "${EMSDK_DIR:-}" && -n "${EMSDK:-}" ]]; then
	EMSDK_DIR="${EMSDK}"
fi

: "${EMSDK_DIR:?Set EMSDK_DIR to your emsdk path (e.g., /opt/emsdk)}"
: "${QT_WASM_DIR:?Set QT_WASM_DIR to your Qt 5.15 wasm prefix (e.g., /opt/qt-wasm)}"

# Load emsdk environment (emcc, node, etc.).
# shellcheck disable=SC1090
EMSDK_DIR_SAVED="${EMSDK_DIR}"
EMSDK_VERSION_SAVED="${EMSDK_VERSION:-}"
source "${EMSDK_DIR_SAVED}/emsdk_env.sh"
if [[ -z "${EMSDK_DIR:-}" && -n "${EMSDK_DIR_SAVED}" ]]; then
	EMSDK_DIR="${EMSDK_DIR_SAVED}"
fi
if [[ -z "${EMSDK_VERSION:-}" && -n "${EMSDK_VERSION_SAVED}" ]]; then
	EMSDK_VERSION="${EMSDK_VERSION_SAVED}"
fi

export PATH="${QT_WASM_DIR}/bin:${PATH}"
export QMAKE="${QT_WASM_DIR}/bin/qmake"

# Pass default memory sizing into qmake if set.
export KONCLUDE_WASM_TOTAL_MEMORY
export KONCLUDE_WASM_PTHREAD_POOL
export KONCLUDE_WASM_PTHREAD_OVERHEAD
export KONCLUDE_WASM_PROCESSOR_COUNT
export KONCLUDE_WASM_PTHREAD_STRICT
export KONCLUDE_WASM_DEBUG
export KONCLUDE_WASM_EXCEPTIONS
export KONCLUDE_WASM_WASM_EXCEPTIONS
export KONCLUDE_WASM_LONGJMP
export KONCLUDE_WASM_STACK_SIZE
export KONCLUDE_WASM_PTHREAD_STACK_SIZE
